### ISSUE TITLE
ArgumentError for some ActiveModel#attribute args on Rails 7 

### ISSUE THREAD

**Issue by jaynetics** [nulldb/nulldb#116]
minimal repro:

```ruby
class MyRecord < ActiveRecord::Base
  attribute :temp_things, :string, array: true
end
```

error:

```
/activemodel-7.0.3/lib/active_model/type/value.rb:8:in `initialize': unknown keyword: :array (ArgumentError)
/activemodel-7.0.3/lib/active_model/type/immutable_string.rb:9:in `initialize'
/activerecord-7.0.3/lib/active_record/type/adapter_specific_registry.rb:24:in `new'
/activerecord-7.0.3/lib/active_record/type/adapter_specific_registry.rb:24:in `block in register'
/activerecord-7.0.3/lib/active_record/type/adapter_specific_registry.rb:60:in `call'
/activerecord-7.0.3/lib/active_record/type/adapter_specific_registry.rb:34:in `lookup'
/activerecord-7.0.3/lib/active_record/type.rb:42:in `lookup'
/activerecord-7.0.3/lib/active_record/attributes.rb:216:in `attribute'
```

**Comment by cabello** [comment]
Wanna try putting a pull request that fixes it? I promise I will review it within 7 days. 🤞
