### ISSUE TITLE
HStore not supported

### ISSUE THREAD

**Issue by axos88** [nulldb/nulldb#118]
```
NoMethodError: undefined method `hstore' for #<ActiveRecord::ConnectionAdapters::NullDBAdapter::TableDefinition:0x000055d56706ab70>
/app/db/schema.rb:115:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-nulldb-adapter-0.8.0/lib/active_record/connection_adapters/nulldb_adapter/core.rb:74:in `create_table'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:929:in `block in method_missing'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:897:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:897:in `say_with_time'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:918:in `method_missing'
/app/db/schema.rb:102:in `block in <top (required)>'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/schema.rb:50:in `instance_eval'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/schema.rb:50:in `define'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/schema.rb:46:in `define'
/app/db/schema.rb:13:in `<top (required)>'
/usr/local/bundle/gems/activerecord-nulldb-adapter-0.8.0/lib/active_record/connection_adapters/nulldb_adapter/core.rb:143:in `load'
/usr/local/bundle/gems/activerecord-nulldb-adapter-0.8.0/lib/active_record/connection_adapters/nulldb_adapter/core.rb:143:in `columns'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:112:in `block in columns'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:111:in `fetch'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:111:in `columns'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:120:in `block in columns_hash'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:119:in `fetch'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/schema_cache.rb:119:in `columns_hash'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:553:in `load_schema!'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/attributes.rb:250:in `load_schema!'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:539:in `block in load_schema'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:536:in `synchronize'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:536:in `load_schema'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:402:in `attribute_types'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/model_schema.rb:428:in `type_for_attribute'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/type_caster/map.rb:16:in `type_for_attribute'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/arel/table.rb:108:in `type_for_attribute'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/table_metadata.rb:18:in `type'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/predicate_builder.rb:63:in `build'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/predicate_builder.rb:58:in `[]'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/predicate_builder.rb:131:in `block in expand_from_hash'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/predicate_builder.rb:84:in `each'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/predicate_builder.rb:84:in `flat_map'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/predicate_builder.rb:84:in `expand_from_hash'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/predicate_builder.rb:29:in `build_from_hash'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/query_methods.rb:1091:in `build_where_clause'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/query_methods.rb:645:in `where!'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/relation/query_methods.rb:640:in `where'
/usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/querying.rb:22:in `where'
```

**Comment by cabello** [comment]
Solved
