### ISSUE TITLE
test suite failures

### ISSUE THREAD

**Issue by ktdreyer** [nulldb/nulldb#56]
I'm seeing the following test failures when I run the tests outside of Bundler. The environment is Fedora 22 with rspec 3.1.0, activerecord 4.1.5, and Ruby 2.1.4.

```
$ rspec -Ilib spec
...-- create_table(:employees)
   -> 0.0001s
...F...........F...F...F......
Failures:
  1) NullDB should remember columns defined in migrations
     Failure/Error: col.type.should == col_type
       expected: :string
            got: nil (using ==)
     # ./spec/nulldb_spec.rb:251:in `should_have_column'
     # ./spec/nulldb_spec.rb:111:in `block (2 levels) in <top (required)>'
  2) NullDB should support migrations
     Failure/Error: Employee.connection.supports_migrations?.should be_true
       expected true to respond to `true?`
     # ./spec/nulldb_spec.rb:172:in `block (2 levels) in <top (required)>'
  3) NullDB should tag logged statements with their entry point
     Failure/Error: cxn.select_values("")
     ArgumentError:
       wrong number of arguments (3 for 1..2)
     # ./lib/active_record/connection_adapters/nulldb_adapter/core.rb:161:in `select_rows'
     # /usr/share/gems/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:44:in `select_values'
     # ./lib/active_record/connection_adapters/nulldb_adapter/core.rb:208:in `block in select_values'
     # ./lib/active_record/connection_adapters/nulldb_adapter/core.rb:239:in `block in with_entry_point'
     # ./lib/active_record/connection_adapters/nulldb_adapter/core.rb:254:in `with_thread_local_variable'
     # ./lib/active_record/connection_adapters/nulldb_adapter/core.rb:238:in `with_entry_point'
     # ./lib/active_record/connection_adapters/nulldb_adapter/core.rb:207:in `select_values'
     # ./spec/nulldb_spec.rb:234:in `block (2 levels) in <top (required)>'
  4) NullDB should support unique indexes
     Failure/Error: Employee.connection.indexes('employees').detect{|idx| idx.columns == ["name"]}.unique.should be_false
       expected false to respond to `false?`
     # ./spec/nulldb_spec.rb:261:in `block (2 levels) in <top (required)>'

```

**Comment by mnoack** [comment]
Closing as this is an old issue and currently the tests do pass on travis, please re-open if this is still relevant.
