### ISSUE TITLE
uninitialized constant ActiveRecord::VERSION (NameError)

### ISSUE THREAD

**Issue by jshumakerpruitt** [nulldb/nulldb#77]
I installed the gem

Gemfile  
`gem 'activerecord-nulldb-adapter'`

and required it in `spec/spec_helper.rb`  

```
require 'nulldb_rspec'
include NullDB::RSpec::NullifiedDatabase
```

I get this error when running `rspec spec`

```rspec spec
/usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/nulldb/extensions.rb:36:in `<module:ActiveRecord>': uninitialized constant ActiveRecord::VERSION (NameError)
        from /usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/nulldb/extensions.rb:34:in `<top (required)>'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/active_record/connection_adapters/nulldb_adapter.rb:10:in `<top (required)>'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/nulldb_rspec.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/jasper/netmon/spec/spec_helper.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `block in requires='
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `each'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `requires='
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `each'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:21:in `configure'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:99:in `setup'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
        from /usr/local/bin/rspec:23:in `load'
        from /usr/local/bin/rspec:23:in `<main>'
```   

rails version 4.2.4

**Comment by jshumakerpruitt** [comment]
adding `require 'active_record/version'` to spec_helper.rb resolves the above error, but then I get this:

```
/usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/nulldb/extensions.rb:36:in `public_send': undefined method `[]' for ActiveRecord::Migration:Class (NoMethodError)
        from /usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/nulldb/extensions.rb:36:in `<module:ActiveRecord>'
        from /usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/nulldb/extensions.rb:34:in `<top (required)>'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/active_record/connection_adapters/nulldb_adapter.rb:10:in `<top (required)>'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/nulldb_rspec.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/jasper/netmon/spec/spec_helper.rb:2:in `<top (required)>'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/2.2/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `block in requires='
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `each'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1394:in `requires='
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `each'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/configuration_options.rb:21:in `configure'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:99:in `setup'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/lib/ruby/gems/2.2/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
        from /usr/local/bin/rspec:23:in `load'
        from /usr/local/bin/rspec:23:in `<main>'
```

**Comment by edwardmp** [comment]
It is probably related to this change I made earlier:
https://github.com/nulldb/nulldb/commit/8df52449251fdc30b40e4e9c4363bb2bc595969b

I know what happens but don't understand why it happens yet. So you are using Rails 4, and I assume ActiveRecord 4 and not 5 right?

**Comment by jshumakerpruitt** [comment]
Yes, that's right.  I'm using 4.2.4.  Would pinning the gem version for nulldb work?

**Comment by mnoack** [comment]
@edwardmp @jshumakerpruitt If I read that line of code correctly it's hitting the case where ActiveRecord::VERSION::MAJOR == 5.

It would be good if @jshumakerpruitt can edit the source code (/usr/local/lib/ruby/gems/2.2/gems/activerecord-nulldb-adapter-0.3.7/lib/nulldb/extensions.rb Line 36) and do some debug statements (puts or byebug) and verify what "ActiveRecord::VERSION" thinks it is.

**Comment by edwardmp** [comment]
@mnoack 
Exactly my thoughts, however it might be easier for @jshumakerpruitt to just execute `ActiveRecord::VERSION::MAJOR` in the Rails console and report back what it returns.

**Comment by jshumakerpruitt** [comment]
```
[2] pry(main)> ActiveRecord::VERSION::MAJOR
=> 4
```

**Comment by edwardmp** [comment]
@jshumakerpruitt 
thanks

@mnoack 
This is really weird. How on earth could it evaluate to the case for AR 5 then?

**Comment by igorescobar** [comment]
Same problem here. Using Rails 5.1.1 with Ruby 2.4.1.

**Comment by edwardmp** [comment]
@jshumakerpruitt which Ruby version are you using?

**Comment by jshumakerpruitt** [comment]
@edwardmp ruby 2.2.6p396

**Comment by Arthaey** [comment]
I had these same errors. I moved the two lines from the suggested `spec_helper.rb` into `rails_helper.rb`, immediately after the requires of spec_helper and the environment file, like so:

```
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)

require 'nulldb_rspec'
include NullDB::RSpec::NullifiedDatabase
```

Then it worked! I assume it's because it needed to run after Rails' files had been required, otherwise the ActiveRecord classes aren't available yet.

(I'm running Ruby 2.3.3 and Rails 5.1.4, FWIW.)

**Comment by jshumakerpruitt** [comment]
Nice catch, @Arthaey.  I required and included the nulldb rspec stuff in an individual spec file and it worked fine.  I agree that the problem seems to be with the order of when the files are required.

**Comment by mnoack** [comment]
Sorry all that I haven't had the time to solve this, but I welcome any PR that fixes this for someone that does have the time.

**Comment by yfaney** [comment]
In my case, adding require 'active_record' before require 'nulldb_rspec' worked for me. You are welcome :)
